kind: Deployment
apiVersion: apps/v1
metadata:
  name: camunda8-wrapper
  namespace: camunda8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda8-wrapper
  template:
    metadata:
      labels:
        app: camunda8-wrapper
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
        - name: camunda8-wrapper
          image: ghcr.io/haninge-digit/digit-camunda-wrapper:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DEBUG
              value: 'false'
            - name: ZEEBE_ADDRESS
              value: camunda8-zeebe-gateway:26500
            - name: MONGO_ROOT_PWD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-password
            - name: DISABLE_AUTH
              value: 'true'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: camunda-wrapper-jwt-secret
                  key: JWT_SECRET
          resources:
            limits:
              memory: "128Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /environment
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /zeebe-engine
              port: http
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: camunda8-wrapper
  namespace: camunda8
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
  selector:
    app: camunda8-wrapper
  type: ClusterIP
